spring:
  application:
    name: api-gateway
cloud:
  gateway:
    routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/api/v1/user/**
      - id: post
        uri: lb://post
        predicates:
          - Path=/api/v1/post/**
#      - id: payment-service
#        uri: lb://payment-service
#        predicates:
#          - Path=/api/v1/payment/**
#      - id: order-service
#        uri: lb://order-service
#        predicates:
#          - Path=/api/v1/order/**, /api/v1/order-detail/**
    discovery:
      locator:
        enabled: true
server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
