server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: lb://user
          predicates:
            - Path=/api/v1/auth/**
        - id: user-follow
          uri: lb://user
          predicates:
            - Path=/api/v1/follow/**
        - id: post
          uri: lb://post
          predicates:
            - Path=/api/v1/post/**
        - id: media-process
          uri: lb://media-process
          predicates:
            - Path=/api/v1/image/**
        - id: feed
          uri: lb://feed
          predicates:
            - Path=/api/v1/feed/**
        - id: challenge
          uri: lb://challenge
          predicates:
            - Path=/api/v1/challenge/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8099/eureka
