spring:
  application:
    name: media-process

server:
  port: 8083

minio:
  bucket-name: true-shot-media
  access-key: test_user
  secret-key: test_password
  url: http://localhost:9000

helper:
  app-ip: ${APP_IP:http://localhost}
  base-url: ${helper.app-ip}:8090
  image-folder-path: /api/v1/image

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
