spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-server: http://localhost:9092
      group-id: trueshot.recent-activities.consumer.notification
      schema-registry-url: http://localhost:8081
      json-use-type-headers: false
      trusted-packages: com.trueshot.notification.dto
      json-value-default-type: com.trueshot.notification.dto.NotificationDTO


server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

application:
  security:
    jwt:
      secret-key: p5VDU8b2L0uOi1TyJ1uyMZmkfXrZStDdp0Kb+7Ksmw0=  # Replace this with your actual JWT secret key

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: trace
