spring:
  application:
    name: challenge
server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

application:
  security:
    jwt:
      secret-key: p5VDU8b2L0uOi1TyJ1uyMZmkfXrZStDdp0Kb+7Ksmw0=

