spring:
  application:
    name: comment
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: http://localhost:9092
    schema-registry-url: http://localhost:8081
    request-timeout-ms: 3000
    max-block-ms: 3000
    post-publish-topic: trueshot.recent-activities.comment

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

application:
  security:
    jwt:
      secret-key: p5VDU8b2L0uOi1TyJ1uyMZmkfXrZStDdp0Kb+7Ksmw0=
